### ISSUE TITLE
[Question] What about local applications?

### ISSUE THREAD

**Issue by jbauer180266** [watson-developer-cloud/questions-with-classifier-ega#50]
Hi,

one final question: If I decided to include similar code in a local application (not on a local application server, but a standalone application, e.g. a JavaFX-based one (but with internet, of course) that talks to the service APIs directly) - would this also work or is there anything that might cause problems?

I know that this is a very general question, but it might become relevant for a particular application I have in mind.

Thank you in advance.

Best wishes,
Joe

**Comment by tdalbo92** [comment]
The APIs aren't technically public, but since it's your deployment you can access them with whatever clients you'd like.  Read up on CORS, if you're unfamiliar with it.  The server is CORS-friendly so you shouldn't run into any issues with that, but whatever client you use will have to be aware of it if it enforces cross-origin policy.

**Comment by jbauer180266** [comment]
Once again: Thank you very much.
