### ISSUE TITLE
Update for CORSFilter

### ISSUE THREAD

**Issue by wangzhidong** [watson-developer-cloud/questions-with-classifier-ega#61]
When use ajax to post rest service, error will happen, for example:

 **           $.ajax({
                url:"http://watson-on-classifier.mybluemix.net/api/v1/conversation/132458"
                type : 'POST',
                data : {"message":"who are you?"},
                contentType: "application/json",
                dataType: 'json',
                success : function(response) {
                    alert("Response from cross origin: " + response);
                },
                error : function(response) {
                    alert(response.responseText);
                }
            });
**

As I check, need to add a line of code in the CORSFilter.java
**sresponse.addHeader("Access-Control-Allow-Headers", "Content-Type");**

**Comment by tdalbo92** [comment]
When you add that line in your local repository and re-run that line of code, does it fix whatever issue you're running into?  

If so, feel free to submit a pull request in the `framework-ega` repository and we'll make sure it gets merged as soon as possible.

**Comment by tdalbo92** [comment]
Also - can you paste the error you're receiving?

**Comment by wangzhidong** [comment]
The error is:
**XMLHttpRequest cannot load http://watson-on-classifier.mybluemix.net/api/v1/conversation/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.**

Yes, after adding that code, will fix this ajax CORS call issue. But I'm going to take vacation, will submit a pull request after vacation. Sorry for that.

**Comment by tdalbo92** [comment]
Not a problem.  I'd have to recommend that you use a simple proxy instead of CORS - that will get you around this issue in a slightly easier way. 

Why do you need CORS though?  If you're building this app and deploying it to your own Bluemix space, you can just replace the HTML and Javascript in /WebApp with the code you're using here.  Then you have your own server, serving your own webpage, and CORS is no longer a problem.

Just a few thoughts to consider.   I'm going to close this Issue, but feel free to make a Pull Request in the `framework-ega` repository so we can get this fixed.  It was our intention to enable CORS on the server :)
